#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue May 16 09:45:46 CEST 2023
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim Test_Banc_de_registre_func_synth -key {Post-Synthesis:sim_1:Functional:Test_Banc_de_registre} -tclbatch Test_Banc_de_registre.tcl -view /home/kanane/Bureau/4A/ProjetSI/project_1/Test_ALU_behav.wcfg -view /home/kanane/Bureau/4A/ProjetSI/project_1/Test_ALU_behav1.wcfg -log simulate.log
